{{- if and .Values.rbac.create .Values.rbac.argoCDRole }}
apiVersion: rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}
kind: Role
metadata:
  name: {{ template "capi2argo-cluster-operator.fullname" . }}-argocd
  labels: {{ include "capi2argo-cluster-operator.labels" . | nindent 4 }}
  namespace: {{ .Values.argoCDNamespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - '*'
{{- end }}
